/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    CommentsList: typeof import('./src/components/Incidents/commentsList.vue')['default']
    CreateComment: typeof import('./src/components/Incidents/createComment.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FilterTable: typeof import('./src/components/Incidents/filterTable.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    IncidentComment: typeof import('./src/components/Incidents/IncidentComment.vue')['default']
    IncidentDetail: typeof import('./src/components/Incidents/incidentDetail.vue')['default']
    IncidentForm: typeof import('./src/components/users/IncidentForm.vue')['default']
    IncidentPanel: typeof import('./src/components/Incidents/IncidentPanel.vue')['default']
    IncidentsState: typeof import('./src/components/Incidents/incidentsState.vue')['default']
    InicidentTable: typeof import('./src/components/Incidents/InicidentTable.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./src/components/auth/loginForm.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
